### ISSUE TITLE
hide columns on mobile 

### ISSUE THREAD

**Issue by hussainkhan4552** [NadavShaar/react-grid-table#109]
@NadavShaar I want to hide some columns on mobile, I am setting visible to false on mobile but it is not working

**Comment by NadavShaar** [comment]
Hi, i am able to change the visibility of columns in the demo page (https://nadavshaar.github.io/react-grid-table/) from my phone, aren't you?

**Comment by hussainkhan4552** [comment]
I want  some of the columns to be hidden on mobile and shown on larger screen for responsiveness

**Comment by NadavShaar** [comment]
Hidden? or removed? you should be able to do so by updating the columns config.

**Comment by hussainkhan4552** [comment]
hidden,
I am changing the visibility of the column but it's not working, visible become false but still, RGT shows that the column

**Comment by NadavShaar** [comment]
Can you please share a live example?

**Comment by hussainkhan4552** [comment]
https://codesandbox.io/s/clever-nightingale-ov2r64?file=/src/App.js 
here is link to the codesandbox you can test it here

**Comment by hussainkhan4552** [comment]
i want user column to be hidden on mobile and shown on larger screen

**Comment by NadavShaar** [comment]
If you want to control the columns you need them updated with the latest changes, to do so, manage them on the state and pass the setState function to `onColumnsChange` and the grid will make sure to update the state when it's changing the columns internally, then add a useEffect that listen to the `isMobile` flag and there you can apply your changes while keeping it synced with the table changes, but make sure to update a new instance of the columns otherwise it won't trigger the change: 
https://codesandbox.io/s/exciting-proskuriakova-6lf36l?file=/src/App.js

**Comment by hussainkhan4552** [comment]
thanks so much for the help, its working fine now.
