### ISSUE TITLE
How to add custom selection in Select All checkbox?

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#39]
@NadavShaar I was just wondering how we can construct a custom selection in the Select All checkbox. Let me explain the scenario!

In the image below grabbed from Gmail inbox as a reference, there is a dropdown arrow next to the select all checkbox which on click triggers a popover and displays some status to select rows from the table.

![image](https://user-images.githubusercontent.com/3774827/103033553-c8b46100-458a-11eb-96ed-a0113e7025c5.png)

**Comment by NadavShaar** [comment]
It was actually considered just today, and I am planning on spending some time on it soon, but it will be available just for a sync table.

Thanks for the suggestion...

**Comment by shivapoudel** [comment]
@NadavShaar Thanks for taking this into consideration. To be honest, I am planning to craft an open-source WordPress plugin utilizing this component from the very first version. Let me explain how this is going to happen, my friend :)

In the WordPress ecosystem, we will fetch the data from the RestApi and there will be definitely infinity rows. Hence we have to fetch them based on row per page so the loading time gets minimized. Do a sync and async support varies in this interesting proposal that could be included but I guess we can polish that separately unless I missed something obvious because of my lack of experience in this area.

**Comment by NadavShaar** [comment]
@ilayofir please add a detailed answer to why implementing this behaviour for async can be tricky.

**Comment by ilayofir** [comment]
Implementing this is sync mode is very easy. We just select all the data instead of the page data. Note that in infinite scroll mode this has the same effect.
But, doing this in async is impossible because we don't have all the ids. The only way I can think of for doing this is to invert the selection when pressing select all, meaning that instead of having a list of selected items you will have a list of unselected items. This approach has the drawback of making the table's api more complicated for users to understand. However, as I can't think of a better solution we will probably implement this at some point.

**Comment by shivapoudel** [comment]
@ilayofir thanks for the clear explanation. I think this feature request can be labeled for future reference :)

**Comment by ilayofir** [comment]
This feature request is very specific. We might implement a select all/none popup at some point, but I can't see us adding support for specific field values (e.g. "starred", "unread" etc.) as it will require too much configuration on the columns, and will never satisfy all use cases. It seems easier for users to implement it themselves if need be.
To implement specific behavior in the checkbox header cell you can pass a custom **HeaderSelectionCell** to the **components** prop. e.g. <GridTable components={{HeaderSelectionCell}}/>. Check out the docs for further information.
Closing this.
