### ISSUE TITLE
Height property is making the loader and no result area collapsed

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#40]
If you remove the height CSS property in `#root` and see the change you will find that the table will be scrollable to the whole content area but the problem is that while doing the search or no result area or loader is displayed then it is hidden just like the screenshot below. Additionally, if we don't want to make the table scrollable but the whole page should be scrollable then there is this issue :)

PS: In the context of WordPress CMS, we cannot apply height to the `#root` area as seen in the below demo because there is admin navigation at the left sidebar, and applying height to make only table scrollable will somehow not be good in presenting the table for me.

![image](https://user-images.githubusercontent.com/3774827/103046078-075c1280-45af-11eb-9e2c-3e3637a68ce1.png)

**Comment by NadavShaar** [comment]
The idea was to make the height as dynamic as it can be, in order to do so, the height of the component's root element (not the element with the id of the root which is not part of the component itself, it is only a wrapper for it) is 100%.
As part of the implementation, the table should be wrapped with a parent element that has the desired height.
I'm not familiar with the WordPress methodology, and why this can be an issue, if wrapping the component in the WordPress ecosystem is an issue, please give me some more details and I'll try to find a solution for it.

Thanks.

**Comment by shivapoudel** [comment]
@NadavShaar I have sent you an email with the login access including steps to replicate this as a design bug in the WordPress sandbox site. Please do check your inbox :)

**Comment by NadavShaar** [comment]
Hi... i saw it, can you tell me if you have access to style the root element of the table component with the class selector of: `awesomeforms-table-wrapper`?

**Comment by NadavShaar** [comment]
Maybe it will be a good idea to have a conference meeting with me and my partner just to understand the limitations of the WordPress ecosystem...
Let me know if you're interested and if so i'll try to schedule one.

**Comment by shivapoudel** [comment]
@NadavShaar That sounds great let's have a talk and discuss further as I was also thinking the same :)

**Comment by NadavShaar** [comment]
Added minimum height of 400px.
