### ISSUE TITLE
Issue while implementing asynchronously fetching data and local search together

### ISSUE THREAD

**Issue by catrawalkar** [NadavShaar/react-grid-table#66]
I have implemented async data using: onRowsRequest prop. Now that I have data of say 100 rows, I have populated it in paginated table with 20 rows in each page (I donot wish to make pagination async).

Now when I perform search, it again hits onRowsRequest function. I understand that this is the expected behaviour because onRowsRequest is supposed to handle everything including **search, sort, etc** 

So I wrote a function onSearchTextChange. I am hoping that I am not calling onRowsRequest within onSearchTextChange and so onRowsRequest should not be called at all. But this is not happening. When searchText changes, onRowsRequest and onSearchTextChange both are getting called.

Am I doing anything wrong here?

```

```

**Comment by catrawalkar** [comment]
Basically, I wish to implement normal local search (which comes out of the box) on aync data. How can I do it?

**Comment by catrawalkar** [comment]
I figured out that, onRowsReset was getting called. So I did ``` controller.abort() ``` in onRowsReset. And then ```tableManager.searchApi.searchRows``` in onRowsRequest

If any more efficient solution, please comment. Else you may close the issue.

**Comment by ilayofir** [comment]
I suppose you can also keep some sort of cache for the fetched rows and simply return the correct ones from the cache when onRowsRequest is called with a searchText. You can even return the "correct" totalRows that way. That said, we will not be implementing this kind of "feature" since it is not a correct way to handle async flows. The data should always be in sync with the sort and searchText. Closing this.
