### ISSUE TITLE
Deprecated API in React StrinctMode

### ISSUE THREAD

**Issue by Pavllick** [NadavShaar/react-grid-table#67]
Hi. I constantly have warnings in browser console about deprecated legacy context API and findDOMNode.
Error seems to appear only in strict mode while development, not in production. And it floods console pretty hardly.

My setup is typescript create-react-app.

![image](https://user-images.githubusercontent.com/7254225/111632772-34454d80-87cb-11eb-9f06-a77b5ebc0968.png)

![image](https://user-images.githubusercontent.com/7254225/111632801-3b6c5b80-87cb-11eb-8c2e-24f4556b1cf7.png)

**Comment by NadavShaar** [comment]
Hi..
Thanks for reporting.
We are aware of this issue which related to one of the dependencies.
We are currently searching to replace that dependency and will update the
table soon.
As for now ignore it, it doesn't affect the package at all.

Thanks!

**Comment by zaweb** [comment]
I'm experiencing similar behavior.

**Comment by NadavShaar** [comment]
Hi and thanks for your reply..
We are aware of this issue which related to one of the dependencies
(react-sortable-hoc), and currently working to find the best solution.
A fixed version will be out soon, hopefully by the end of this month.
BTW, as far as i know, it won't have any negative effect on the
functionality, and it's more of a warning rather than an error at this
stage.
Stay tune..

**Comment by zaweb** [comment]
Thank you for the reply. Just to be clear: my post was just informational and wasn't meant to imply any sort of urgency. I've been trying out GridTable and really like it so far; it's a great solution for what I'm trying to achieve. Thank you!

**Comment by NadavShaar** [comment]
Fixed in version 0.3.0

**Comment by zaweb** [comment]
Working great, thank you so much for the fix!
