### ISSUE TITLE
Why every api hooks use useRef then return current value ?

### ISSUE THREAD

**Issue by ccaa7530** [NadavShaar/react-grid-table#77]
Hi, I am very interested to understand why you use the reference in the hook and then return the reference current value.
Can you share why you designed it this way ? 
Is it to prevent re-rendering during recalculation ?

like this.
```
const columnsApi = useRef({}).current;
```

**Comment by ilayofir** [comment]
It is designed this way so the APIs would retain their original reference. Basically we are utilizing the useRef hook to mimic the  "this" reference.

Or - If you are using the "onLoad" event to get the grid API from your parent component or whatever, you will get an object with a bunch of API objects that contain various functions/hooks that can be utilized to manipulate the grid. These API objects need to keep their references because react-grid-table will periodically update the functions/hooks if one of their dependencies change, and so the grid API that was received in the "onLoad" event would now be out of sync and its internal functions might reference obsolete functions.

Hope this answers your question :)
